- app/Protocols/Loon.php
new：Loon 支持下发vless字段，但暂时不支持Reality, 因为 Loon 官方支持Vless,但是还不不支持新Reality.
> new：Loon支持下发vless字段，但暂时不支持Reality

- app/Protocols/Loon.php
- app/Protocols/Stash.php
fix: 修正Loon WS+TLS时over-tls始终为false问题
fix: 将Stash暂不支持的Flow均替换为none,避免无法启动Stash
> 一些 Stash 和 Loon 的字段下发问题修正

- cli-php.ini
Added SSL CA certificate settings to ensure secure connections during HTTPS requests.
> add ssl ca certificate settings

- app/Http/Controllers/V1/Client/AppController.php
> 修复webman获取订阅502（APP）

- app/Http/Controllers/V1/User/TicketController.php
Ticket Telegram Bot Enhancements
> Ticket Enhancements

- app/Protocols/V2rayN.php
- app/Protocols/V2rayNG.php
> v2rayn - v2rayng

- app/Console/Commands/ClearUser.php
Fix deprecated variable interpolation while php version > 8.0
> Fix deprecated variable interpolation

- app/Protocols/ClashNyanpasu.php
参考https://nyanpasu.elaina.moe/zh-CN/others/faq#_5-%E7%BC%BA%E5%B0%91%E8%AE%A2%E9%98%85%E8%8E%B7%E5%8F%96%E8%8A%82%E7%82%B9%E7%B1%BB%E5%9E%8B
> 增加Clash Nyanpasu支持，可获取到vless、hy2等协议的节点

- app/Http/Controllers/V1/Client/ClientController.php
- app/Protocols/Hiddify.php
此前Hiddify订阅以singbox配置处理，无法正常显示订阅信息
> 增加Hiddify订阅信息显示

- app/Http/Controllers/V1/User/TicketController.php
我看了一下更新后的TicketController把这个给删了，导致用户可以串台看别人工单，就加回来了
> 加回了工单的用户检查

- app/Http/Controllers/V1/Admin/StatController.php
- app/Protocols/Loon.php
> Linger040831 patch 1

- app/Protocols/Loon.php
- app/Protocols/Stash.php
- app/Protocols/Surge.php
Clients affected:
- Surge
- Loon
- Stash
> feat(protocol): add ss2022 support for iOS clients

- app/Protocols/Loon.php
- app/Utils/Helper.php
> 增加vmess可选ws加密类型

- app/Http/Requests/Admin/ServerVmessSave.php
- app/Protocols/Clash.php
- app/Protocols/ClashMeta.php
- app/Protocols/Loon.php
- app/Protocols/QuantumultX.php
- app/Protocols/Shadowrocket.php
- app/Protocols/Singbox.php
- app/Protocols/Stash.php
- app/Protocols/Surfboard.php
- app/Protocols/Surge.php
- app/Utils/Helper.php
增加vmess加密类型检测、前端保存提示，避免加密类型设置错误，适配各个客户端
> 增加vmess加密类型检测、前端保存提示，避免加密类型设置错误，适配各个客户端

- app/Services/ServerService.php
- app/Utils/Helper.php
已在Xboard中shadowrocket和V2rayNG订阅通过测试，其他订阅未测试
解决 #96
> 使订阅中 ss 支持 obfs 参数

- app/Http/Controllers/V1/User/UserController.php
giftcard_end字段错误，导致无法正确判断gift过期
> fix giftcard_ended

- app/Protocols/QuantumultX.php
* Add VLESS support
* Add VMess Http Transport support
* TLS Default use TLS1.3
> Protocols: QuantumultX: Add VLESS support & Minor Changes

- app/Protocols/QuantumultX.php
> Fix networkSettings

- resources/rules/default.sing-box.old.json
修复旧版sing-box弃用警告
[default.sing-box.old.json](https://github.com/user-attachments/files/20105779/default.sing-box.old.json)
> 修复旧版sing-box弃用警告

- app/Plugins/Telegram/Commands/GetLatestUrl.php
> fix command description

- app/Protocols/Loon.php
> fix:修复 Loon订阅 vless+tcp+tls 缺少流控

- app/Payments/BEasyPaymentUSDT.php
项目地址：
https://github.com/v03413/BEpusdt
API & 支持的区块网络类型：
https://github.com/v03413/BEpusdt/blob/main/docs/api.md
https://github.com/v03413/BEpusdt/blob/main/docs/trade-type.md
> app: Payments: add BEpusdt support
